export const FETCH_MOVIES = 'FETCH_MOVIES';

export const FETCH_PLANETS_PENDING = 'FETCH_PLANETS_PENDING';
export const FETCH_PLANETS_FULLFILED = 'FETCH_PLANETS_FULLFILED';
export const FETCH_PLANET_FULLFILED = 'FETCH_PLANET_FULLFILED';
export const FETCH_PLANETS_REJECTED = 'FETCH_PLANETS_REJECTED';